### ISSUE TITLE
SocketError: other side closed

### ISSUE THREAD

**Issue by ShrimpAIO** [nodejs/undici#583]
Upon connecting to a proxy with user:pass it's all good, but when I try to make a request to an proxy which is IP authenticated, I get 'SocketError: other side closed'. 
I'm not sending the proxy-authorization header as it's not needed.
Blanked the proxy ip and port below.
```js
var Client = require('undici');
(async ()=>{
	const client = new Client("http://proxyip:proxyport")
	const response = await client.request({
	  method: 'GET',
	  path: 'https://api.ipify.org?format=json',
	  headers: {
	    //'proxy-authorization': `Basic ${Buffer.from(':').toString('base64')}`
	  }
	})

	response.body.setEncoding('utf8')
	let data = ''
	for await (const chunk of response.body) {
	  data += chunk
	}
	//
	console.log(response.statusCode)
	console.log(JSON.parse(data))

	client.close()
})();
```

**Comment by Ethan-Arrowood** [comment]
@ShrimpAIO do you have an example with another HTTP client of this working?

**Comment by ShrimpAIO** [comment]
> 
> 
> @ShrimpAIO do you have an example with another HTTP client of this working?

`
var res = await superagent
.get('https://api.ipify.org?format=json')
.proxy(proxyUrl);`
Blanked out the proxy above but the above code works on Superagent. Also worked on Axios & request-proxy. Just for some reason they refuse to work with Undici.

**Comment by ShrimpAIO** [comment]
`node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

SocketError: other side closed
    at Socket.onSocketEnd (D:\Libraries\Documents\Undici\node_modules\undici\lib\core\client.js:773:22)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'UND_ERR_SOCKET'
}`
Incase this is any help - here's a fuller error log

**Comment by ShrimpAIO** [comment]
> 
> 
> So from what I can gather these other HTTP clients may be automatically adding things to the request for you. I'd recommend logging the complete request from something like `superagent` and see what else is being sent over. Compare that to `undici` and go from there.

I've made some progress but still not working with these particular proxies.
Adding browser-like headers to the request on Windows presents this:
<html><head><title>400 Bad Request</title></head>
<body><h2>400 Bad Request</h2></body></html>

400
Meanwhile, the same code on Ubuntu throws me this:

SocketError: other side closed
    at Socket.onSocketEnd (/home/ubuntu/Crustacean/Monitors/Shopify/node_modules/undici/lib/core/client.js:773:22)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UND_ERR_SOCKET'
}

The IP's are 100% authenticated as the superagent code works both on Ubuntu and Windows.

**Comment by ShrimpAIO** [comment]
Seems like another proxy provider refuses to work;
Bad Protocol
403
This one was user:pass authenticated.
There are two providers I have access to that fully work, but proxy support does seem iffy.

**Comment by Ethan-Arrowood** [comment]
Maybe this is something not yet achievable in Undici see #569

**Comment by Ethan-Arrowood** [comment]
And #568 might help you too

**Comment by ShrimpAIO** [comment]
Ok;
The two issues above did not help, another discovery has however been made - only http requests can be successfully made, the moment a request is https these proxies do not like it and throw odd errors

**Comment by MysticEarth** [comment]
This also happened to me when making a normal request to for example "http://nvidia.com" using the example from the Quickstart. I *do* get some response but after that my app crashes:

```bash
response received 302
headers {
  location: 'http://www.nvidia.com/',
  'content-type': 'text/html',
  'cache-control': 'private',
  connection: 'close'
}
```

The application crashes on:

```json
events.js:292
      throw er; // Unhandled 'error' event
      ^

SocketError: other side closed
    at Socket.onSocketEnd (/Users/<my-username>/<my-project>/node_modules/undici/lib/client.js:916:22)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on RequestResponse instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UND_ERR_SOCKET'
```

**Comment by ronag** [comment]
Do you have the same problem with 4.0.0-alpha.2?

**Comment by MysticEarth** [comment]
Just tried and this still happend with 4.0.0-alpha.2

**Comment by ronag** [comment]
Can you please provide a repro?

**Comment by MoritzLoewenstein** [comment]
I had a pretty similar error:
```
node:events:342
      throw er; // Unhandled 'error' event
      ^

SocketError: other side closed
    at TLSSocket.onSocketEnd (/home/path/undici-fetch-repro/node_modules/undici/lib/core/client.js:781:22)
    at TLSSocket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on RequestResponse instance at:
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'UND_ERR_SOCKET'
}
```

I build a small reproduction, its just requesting a lot of files one by one from cloudfront.
See here: https://github.com/MoritzLoewenstein/undici-fetch-repro

**Comment by MoritzLoewenstein** [comment]
![grafik](https://user-images.githubusercontent.com/32882329/119040178-5fa80c80-b9b5-11eb-92cd-e851e7a94fcc.png)
(pinging because you asked for a reproduction) @ronag 
Can anyone confirm this issue with my provided [reproduction repo](https://github.com/MoritzLoewenstein/undici-fetch-repro)?
If its helpful i can create a new issue but I think its the same underlying problem, and should be labeled a bug.

**Comment by mcollina** [comment]
@MoritzLoewenstein  Could you use a Node.js server to reproduce?

**Comment by MoritzLoewenstein** [comment]
Hey, I added a node server. The issue is indeed an invalid Content-Length header, if I don't set the Content-Length header on the server I cant reproduce the issue.
When I copy the Content-Length value from the cloudfront / s3 response it will crash after 10-15k tries.

**Comment by mcollina** [comment]
> The issue is indeed an invalid Content-Length header

Do you know what's the value of this?

**Comment by MoritzLoewenstein** [comment]
When I dont set the Content-Length header, node will set the Transfer-Encoding header to chunked (= no Content-Length header).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding
22661 is apparently the correct filesize for the test image:
![grafik](https://user-images.githubusercontent.com/32882329/119119145-37f38b80-ba2b-11eb-8acc-163168257241.png)

**Comment by mcollina** [comment]
Can you prepare an example to reproduce the problem? You can also use a `net` server and send out HTTP in text form.

**Comment by MoritzLoewenstein** [comment]
My provided example should be sufficient to show the problem: https://github.com/MoritzLoewenstein/undici-fetch-repro
It doesnt reproduce the problem on every request, but after around 10k to 15k requests the uncaughtException occurs.

I investigated a bit more: When the code enters `onSocketEnd` in `client.js`, the error will happen 100% of the time (but `onSocketEnd` doesnt happen everytime).
here is the parser printed in this function:
```
<ref *1> Parser {
  ptr: 88736,
  client: <ref *2> Client {
    _events: [Object: null prototype] {
      drain: [Function: onDrain],
      connect: [Function (anonymous)],
      disconnect: [Function (anonymous)]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    [Symbol(kCapture)]: false,
    [Symbol(url)]: URL {
      href: 'http://localhost:3000/',
      origin: 'http://localhost:3000',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    [Symbol(connector)]: [Function: bound connect],
    [Symbol(socket)]: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'localhost',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(async_id_symbol)]: 11,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: true,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(no ref)]: false,
      [Symbol(connecting)]: false,
      [Symbol(writing)]: false,
      [Symbol(reset)]: false,
      [Symbol(error)]: null,
      [Symbol(parser)]: [Circular *1],
      [Symbol(client)]: [Circular *2]
    },
    [Symbol(pipelinig)]: 1,
    [Symbol(max headers size)]: 16384,
    [Symbol(connect timeout value)]: 10000,
    [Symbol(default keep alive timeout)]: 4000,
    [Symbol(max keep alive timeout)]: 600000,
    [Symbol(keep alive timeout threshold)]: 1000,
    [Symbol(keep alive timeout)]: 4000,
    [Symbol(closed)]: false,
    [Symbol(destroyed)]: false,
    [Symbol(server name)]: null,
    [Symbol(destroy callbacks)]: [],
    [Symbol(resuming)]: 0,
    [Symbol(need drain)]: 2,
    [Symbol(host header)]: 'host: localhost:3000\r\n',
    [Symbol(body timeout)]: 30000,
    [Symbol(headers timeout)]: 30000,
    [Symbol(strict content length)]: true,
    [Symbol(queue)]: [ [Request] ],
    [Symbol(running index)]: 0,
    [Symbol(pending index)]: 1,
    [Symbol(needDrain)]: true
  },
  socket: <ref *3> Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: 'localhost',
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: true
    },
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function: onSocketError],
      data: [Function: onSocketData],
      close: [Function: onSocketClose]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    write: [Function: writeAfterFIN],
    [Symbol(async_id_symbol)]: 11,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      [Symbol(owner_symbol)]: [Circular *3]
    },
    [Symbol(kSetNoDelay)]: true,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(no ref)]: false,
    [Symbol(connecting)]: false,
    [Symbol(writing)]: false,
    [Symbol(reset)]: false,
    [Symbol(error)]: null,
    [Symbol(parser)]: [Circular *1],
    [Symbol(client)]: <ref *2> Client {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      [Symbol(kCapture)]: false,
      [Symbol(url)]: [URL],
      [Symbol(connector)]: [Function: bound connect],
      [Symbol(socket)]: [Circular *3],
      [Symbol(pipelinig)]: 1,
      [Symbol(max headers size)]: 16384,
      [Symbol(connect timeout value)]: 10000,
      [Symbol(default keep alive timeout)]: 4000,
      [Symbol(max keep alive timeout)]: 600000,
      [Symbol(keep alive timeout threshold)]: 1000,
      [Symbol(keep alive timeout)]: 4000,
      [Symbol(closed)]: false,
      [Symbol(destroyed)]: false,
      [Symbol(server name)]: null,
      [Symbol(destroy callbacks)]: [],
      [Symbol(resuming)]: 0,
      [Symbol(need drain)]: 2,
      [Symbol(host header)]: 'host: localhost:3000\r\n',
      [Symbol(body timeout)]: 30000,
      [Symbol(headers timeout)]: 30000,
      [Symbol(strict content length)]: true,
      [Symbol(queue)]: [Array],
      [Symbol(running index)]: 0,
      [Symbol(pending index)]: 1,
      [Symbol(needDrain)]: true
    }
  },
  timeout: Timeout {
    _idleTimeout: 30000,
    _idlePrev: [Timeout],
    _idleNext: [TimersList],
    _idleStart: 61,
    _onTimeout: [Function: onParserTimeout],
    _timerArgs: [Array],
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: false,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 18,
    [Symbol(triggerId)]: 16
  },
  timeoutValue: 30000,
  timeoutType: 2,
  statusCode: 200,
  upgrade: false,
  headers: [],
  headersSize: 0,
  headersMaxSize: 16384,
  shouldKeepAlive: true,
  paused: true,
  resume: [Function: bound resume],
  bytesRead: 22661,
  trailer: '',
  keepAlive: 'timeout=5',
  contentLength: '22661'
}
```

**Comment by mcollina** [comment]
It's not enough for a unit test.

**Comment by MoritzLoewenstein** [comment]
Alright, I will see if I can narrow it down.

**Comment by mcollina** [comment]
> Alright, I will see if I can narrow it down.

Thanks! Tracking down those conditions is hard :(.

**Comment by MoritzLoewenstein** [comment]
The reason undici crashes is an incorrect `Transfer-Encoding` header on the server:
per default my test server would not set this header at all, but apparently still send the content
according to `Transfer-Encoding: "chunked"`.
If I manually set the header on the server, everything works fine.

One more thing I found out in the process, undici will keep the node process open if
`Connection: "keep-alive"` & `Keep-Alive: "timeout=5"` headers are set (for as long as the timeout lasts).
node-fetch will close instantly after the request has finished (not sure who is "wrong" or if this is even a problem).

Current reproduction with server & files is here: https://github.com/MoritzLoewenstein/undici-fetch-repro

**Comment by MoritzLoewenstein** [comment]
Ok, I have written a test that will fail, but I think I cant push it because of that.
<details> 
  <summary>here is the code for the test:</summary>

   ```js
  test('dont crash on unexpected Transfer-Encoding Header', async (t) => {
     t.plan(2)
  
    const server = createServer((req, res) => {
      res.setHeader('Content-Type', 'text/plain')
  
      res.removeHeader('Connection')
      res.removeHeader('Keep-Alive')
      res.removeHeader('Transfer-Encoding')
      const str = 'Chunked Transfer Encoding Test'
      res.write(str.repeat(832))
      res.end(str)
    })
    t.teardown(server.close.bind(server))
  
    server.listen(0, async () => {
      const client = new Client(`http://localhost:${server.address().port}`)
      t.teardown(client.destroy.bind(client))
  
      process.on('uncaughtException', () => {
        t.fail('uncaughtException happened')
      })
      try {
        await client.request({
          path: '/',
          method: 'GET'
        })
        t.pass('request successful')
      } catch (err) {
        t.pass('error happened')
      } finally {
        process.removeListener('uncaughtException')
      }
    })
  })
   ```

**Comment by mcollina** [comment]
Your test does not run successfully, it has some issues with promises, callbacks and how tap needs things laid out. 

However, I have adapted your test to run and it passes on master (see https://github.com/nodejs/undici/pull/822).
Have you tried v4.0.0-rc.5?

My understanding is that this is fixed.

**Comment by mcollina** [comment]
(You can push a failing test with `git commit -n`)

**Comment by MoritzLoewenstein** [comment]
Im sorry for the incorrect test, but the issue still happens on rc5. Apparently the issue only occurs when not doing anything with the response body, because you called `body.resume` and it doesnt happen in that scenario. Also just reading and printing the body prevents it:
```
const { body } = await undici.request("http://localhost:3000");
  for await (const data of body) {
    console.log("data", data);
  }
```
I dont know how common this is but my original use case was to just read the response headers, status code etc and do nothing with the body.

**Comment by ronag** [comment]
You need to consume or destroy the response body. I think the docs mention this.

**Comment by MoritzLoewenstein** [comment]
I wasnt aware of that and couldnt find it in the docs, but if that is the case it should be handled in undici-fetch i guess?

**Comment by ronag** [comment]
Yea I can’t find it either now. Maybe got lost when we did the docs overhaul. PR welcome!

**Comment by istarkov** [comment]
I'm still having this bug with 4.0.0-rc.7, what is wrong?

```typescript
import type { RequestHandler } from '@sveltejs/kit';
import pkg from 'undici';
const { Pool } = pkg;

// process.env.API_ORIGIN would be killed by vite (bug), so hack
const client = new Pool(
  process['env']['API_ORIGIN'] ?? 'http://localhost:6543',
);

export const post: RequestHandler = async req => {
  // We are waiting this https://github.com/sveltejs/kit/issues/1563
  // to complete, then we must switch to previous implementation, preserving compression etc
  try {
    const headers: Record<string, string | string[]> = {
      'content-type': 'application/json; charset=utf-8',
    };

    const data = await client.request({
      path: '/v1/graphql',
      method: 'POST',
      body: JSON.stringify(req.body),
      headers,
    });

    let strBody = '';
    for await (const chunk of data.body) {
      strBody += chunk;
    }

    const allowedHeaders = [
      'content-encoding',
      'content-type',
    ];

    const headersOut: Record<string, string> = {};

    for (const allowedheader of allowedHeaders) {
      const headerValue = data.headers[allowedheader] as string;
      if (headerValue != null) {
        headersOut[allowedheader] = headerValue;
      }
    }

    return {
      headers: headersOut,
      body: strBody,
    };
  } catch (e) {
    console.error('ERROR: error occured at graphql.js handler', e.message);
    console.error(e);
    throw e;
  }
};
```

**Comment by moises-marquez** [comment]
I'm facing a similar error, but with `fastify-http-proxy` which uses `undici` underneath. The server stops with an unrecoverable error when the request is suddenly closed:

```
{"level":40,"time":1629317990531,"pid":12743,"hostname":"moises-minna","reqId":"req-q","name":"SocketError","code":"UND_ERR_SOCKET","stack":"SocketError: other side closed\n    at Socket.onSocketEnd (/my_project/node_modules/undici/lib/client.js:1050:22)\n    at Socket.emit (events.js:388:22)\n    at Socket.emit (domain.js:470:12)\n    at endReadableNT (internal/streams/readable.js:1336:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","type":"Error","msg":"response errored"}

/my_project/node_modules/fastify/lib/request.js:150
      return this.socket.remoteAddress
                         ^
TypeError: Cannot read property 'remoteAddress' of null
    at _Request.get (/my_project/node_modules/fastify/lib/request.js:150:26)
    at Object.asReqValue [as req] (/my_project/node_modules/fastify/lib/logger.js:55:26)
    at Pino.asJson (/my_project/node_modules/pino/lib/tools.js:118:50)
    at Pino.write (/my_project/node_modules/pino/lib/proto.js:201:28)
    at Pino.LOG [as error] (/my_project/node_modules/pino/lib/tools.js:55:21)
    at defaultErrorHandler (/my_project/node_modules/fastify/fastify.js:81:15)
    at handleError (/my_project/node_modules/fastify/lib/reply.js:550:20)
    at onErrorHook (/my_project/node_modules/fastify/lib/reply.js:521:5)
    at _Reply.Reply.send (/my_project/node_modules/fastify/lib/reply.js:127:5)
    at onErrorDefault (/my_project/node_modules/fastify-reply-from/index.js:209:9)

```

**Comment by razuro** [comment]
For me, this only happens inside Docker (container fetching from another container). It will run OK, if I run it from my localhost (localhost code fetching from another localhost). 

When inside Docker, it can resolve the IP or hostname, but will produce the error above, regardless of node version, tried most v18 and v20.

The only fix for me is, unfortunately to use other http client package (Axios/Superagent).

**Comment by metcoder95** [comment]
This issue has been closed since 3 years ago; please open a new one with a description and an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) if possible 🙂

**Comment by WilfredAlmeida** [comment]
I'm still facing the issue in 2024.

For anyone pulling their hair over this, this issue is not at all encountered with the bun runtime, give it a shot.

**Comment by iscekic** [comment]
Any update on this? I'm consuming the body with `await body.json()`, yet this error still seems to be intermittently reported.

**Comment by WilfredAlmeida** [comment]
I have managed to fix this and other socket errors in my applications by limiting the nuber of connections NodeJS is allowed to open to the server. I observed that the node process was opening too many connections to the server, that is, using too many local ports of the host (16000+ in my case) and eventually these connections would end abruptly and cause the error.

The number of connections can be limited via setting the `connections` param in the `httpAgent`
```
https.Agent({
  maxSockets: 50,
})
```

50 might not be an ideal number for you and you might still face the issue or your application might slow down because the process has lesser number of connections. You need to trial and error and find a number that works for you. 100 worked well for me when I did over 2 million async API calls for testing the limits.

You can monitor the number of ports used by your node process on unix based systems via the following command
```
lsof -i -n -P | grep node | awk '{print $9}' | awk -F '->' '{print $1}' | awk -F ':' '{print $2}' | sort -u | wc -l
```

Bun used around 400-500 ports and was faster than NodeJS. I've tested using `node v20.13.1` and `bun 1.1.8` on my local

I haven't dug into whether the OS limits the number of connections, runs out of them or NodeJS is unable to handle them

If this doesn't fix the issue for you and you want to dig in further, a packet capture can be helpful. I did a pcap and analyzed the packets in Wireshark. You'd want to look for the flow, source, destination, origin of the `SYN`, `SYN/ACK`, `RST` packets. The expert analysis tool in Wireshark does a great job at adding clarity as well.

Also, if the server you're connecting to has rate limits, give a look at what it does to new connection requests and exising connections once the limits are hit

Overall, this issue is now fixed for me and for all of the people I've recommended the above mentioned fix.

**Comment by aleluff** [comment]
The bug can popup when the disk is full also

**Comment by WilfredAlmeida** [comment]
@aleluff This may be one of the cause as well. I had plenty of disk space available during working on this.

**Comment by dankolz** [comment]
fwiw, I was able to reproduce this consistently while running the VS Code interactive debugger on test cases of some api code I was writing using the `fetch` function. If I paused for more than a few second the next `fetch` call would result in the error.

I assume there's other ways to fix this, but adding

```
Connection: close
```
to the request headers seems to have avoided it for now.

**Comment by neoncube2** [comment]
For anyone following this bug, here's the latest open issue for this error: https://github.com/nodejs/undici/issues/3492
